### PR TITLE
Add snap packaging

### PR DESCRIPTION
**Pull request by artivis**
This PR adds [snap](https://snapcraft.io/about) packaging to `rosshow`.

To give it a shot, first install it:

```bash
snap install rosshow --edge
```

And off you go:

```bash
rosshow <topicname>
```

You don't even need ROS to be installed on the host to use it since the snap packages all `rosshow` dependencies.

At the moment [I own the 'rosshow' name on the snap store](https://snapcraft.io/rosshow); I'd be more than happy to transfer it to you.

Please, feel free to ping me with any question you might have.

A few notes:

- The snap currently on the store was packaged based on `Noetic`. Altho I tested it fine against my `Melodic` simulation. I've tested a bunch of messages but not the complete list from the readme.
- I've rename `librosshow` to `rosshow` throughout the codebase. Not sure why this was named `librosshow` since the project and module are named `rosshow`. Without this change, I can't get the project to work when compiled with `caktin_make_isolated`.
- The ROS 1 / ROS 2 `CMakeLists.txt` & `package.xml` are merged together similarly to what's done in `rosboard`.
- I've added every dependency that explicitly appears in the codebase to the `package.xml` file so that e.g. `rosdep` can install them.

--- 

Marked as draft until https://github.com/snapcore/snapcraft/pull/3570 gets merged.

### CODE REVIEW

**Comment by dheera** [comment]
Hi,
Thanks so much for this!
I recently renamed `librosshow` -> `rosshow` as I'm migrating it to a dual ROS1/ROS2 package but I think I forgot to update all the references to the module in the code, and my tests had passed only because I happened to have `librosshow` still in my filesystem -- thanks for catching them, and in the future I'll do tests in a fresh docker instead of my main system to avoid this kind of situation happening again.

I still do need to study a bit more how Snap packaging works and the Snapcore pull request but since the PR seems to not affect traditional non-Snap install I've merged it for now and will circle back to it after I've looked into how it works. I may want to transfer ownership at some point just to keep everything in one place, but thank you for starting this!

Thanks!

**Comment by artivis** [comment]
Hi @dheera,
my apologies I should have marked this PR as 'draft' until https://github.com/snapcore/snapcraft/pull/3570 gets merged. I'm afraid you won't be able to build the snap yourself at the moment.
Anyway feel free to ping me shall you have any question.

**Comment by artivis** [comment]
Looks like our messages crossed path :).

Well, thank you for developing this open source tool! Once again, feel free to ping me on any snap related question and we can deal with the ownership transfer once you feel up to speed.

ps: Don't worry about the snapcore/snapcraft PR, it simply add support for conditions in package.xml files to snapcraft ;).

**Comment by dheera** [comment]
Yep, I realized that. I merged it mainly because the artifact of `librosshow` instead of `rosshow` was in fact breaking it for people who did not previously install rosshow so thanks for that! Ideally maybe it would have been 2 PRs but that's okay for now since there aren't currently snap users and that doesn't break any existing features.

**Pull request merged**
